### ISSUE TITLE
Change domain name of webpage

### ISSUE THREAD

**Issue by sascha-kirch** [sascha-kirch/sascha-kirch.github.io#1]
I'd like to change the path of my website to mention my full name, not my github account name

**Comment by SaKi1309** [comment]
IS related to the username. USer name can be changed: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-user-account-settings/changing-your-github-username

**Comment by sascha-kirch** [comment]
NAme has been changed to sascha-kirch
